<?php
require_once ('include/common.php');
require_once ('schedule/tasks.class.php');
require_once ('running_sched/schedule2.class.php');
require_once ('pdf/HTML_toPDF/HTML_ToPDF.php');
require_once ('include/header.php');

$schedule = new schedule();

$_REQUEST['view_community'] = "396e59697add2cef890e2057c61df9dd";
$_REQUEST['wrap'] = 1;
$_REQUEST['view'] = 2;
$_REQUEST['GoToDay'] = 1140411600;

reset($schedule->active_lots);
while (list($community_hash,$community_array) = each($schedule->active_lots)) { 
	if (($_REQUEST['view_community'] && $community_hash == $_REQUEST['view_community']) || (!$_REQUEST['view_community'] && count($community_array['lots']) > 0)) {
		$lot_c++;
		$html = $schedule->running_schedule_wrap_printable($community_hash,$community_array);
	} 
}

$defaultDomain = LINK_ROOT."core";
$pdfFile = SITE_ROOT.'core/user/printable_schedule_'.$_SESSION['id_hash'].'.pdf';
$htmlFile = SITE_ROOT.'core/user/printable_schedule_'.$_SESSION['id_hash'].'.html';
unlink($pdfFile);

$fh = fopen($htmlFile,"w");
fwrite($fh,$html);
fclose($fh);

$pdf =& new HTML_ToPDF($htmlFile, $defaultDomain, $pdfFile);
// Set headers/footers

$pdf->setHtml2Ps("/usr/local/bin/html2ps");

$pdf->setHeader('color', 'blue');
$pdf->setFooter('left', 'Generated by HTML_ToPDF');
$pdf->setFooter('right', '$D');
$pdf->setUseColor(true);

$result = $pdf->convert();

// Check if the result was an error
if (PEAR::isError($result)) {
    die($result->getMessage());
}
else {
	header("Location: ".$defaultDomain."/user/".basename($result));
	exit;
}

?>